language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
install: true
addons:
  sonarqube:
    organization: "jdbdt" 
    token:
      secure: "tPenh/HFqxoNMVSZLW/d/v9i6bpaXM1FTYWfZptq7OAk/qxYQr1GDVVYhWHj9BS+FckKaNLsKLUnbNBVepv9c8ND6jNNcFVYrVy07MBkyEf+U8NblwX8b7uC/+EiD1Q1eJp8aBK9Gq9sQEnSN9pjnUhoWh4WLaCZOsNxWiNceXyOUG9qWBFvB8+FuB6o+OQigbF9Gg6NfICizO5D6BCe1YuFS+dFOtQmSWngoH82LPCgRICZVN17fUEEvnuvAwIvFFAnhSoaaQCKryEgBlkDsbjLXx18lvpuF88rt8iZGAZWlNHAxNZ1bc1mMAl8vMV6zKiTX/R84tsiKpQrNxfc4gQx09SofuOhBZHG3V8EE29RsBuyeBZwhvK2foQhrCu1IzWEMWixQ1uNFHSJPLu/T4J4+Nv0St5XRtU1c24rFc/1bwlhFthfMgVbChmPgjHlp7ye8sk82/c75ccgS3alAa6Ru1k8sT3YrqJvgKuponbEyx4OhTpYUWe2jWm4DPCWgsEd8D7hKpCngx+zQZjQAQesHMownxGUHoHeIibhZYRlon1V5LBJtYSwZSwKV9ZdKfNdBwjQz2/OymL4hgLA+yqoy/aCckJR/Hzw9wd1vq/2ENPqPYYarMsJ914cEJejXC3+oZ8c72Y6Tyu/DvTYiyI8HzC2S0gtt6FyvwfOMoM="
      secure: "rCWJ+3KyKvJJAQt/3yTI6/XUfpjQVgmSCPk5doo4DDLWmFW1D/UxDYcu7nsGMGkL7wLRY8kb+BJmF8SaA/iYDGKsiNm4j36WwtBPXTWt8YfDqqnqPx4X722xLfXEmtpDQALtFo4+vZu9wKh6ep4vKnGahQ+MvWOSMrE4n29C0xRfuo/DCXvNpFG+4A46uMbZp8kH8RwLTs94zf+6+5Rym98ZWS4wJ4VH7fZR+81qs7KvJbf/UMGeG4pRw+tRAMQYBCHBYwL/xPYFgpeZaqkbUxvTQF131dIOItTC8+/pWQit2al+RywUHq5Sh9HbxoGCdw0oMgBo8nBCAgRypRWjejNslYqxes25R4JgCZYZOVCBKm4FEn27tmh248z66fEKblVVHYbC/X8BJG7eXCFHlGcDaAdoeaJ+Z3UFFzDgTbZYYLhmwp4lCxVhueFWP7hK2XujKZeH0eFrBSpDzYusVxeFinGBRpx9bDm7MgvpYAQsu5CiTP91DzNWA3duIvEhhKWD3OwKUT/WA0fEpYZ0LQCwregqE7SMozcNVaYnsFaseitj3hjfeAvsRuxMM5qJtZR7MWwFortYyYc4lNfiJMgKBQgC543MzVNl+8lPNFgwtZ264XzDFRLc1LSKcyMjaGKip7zzbTPYJkzE6p26aVZHCWp6047kLYboqN1fzu0="
script: 
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 
