CREATE TABLE USERS 
(
   ID INTEGER PRIMARY KEY NOT NULL ,
   LOGIN VARCHAR(16) UNIQUE NOT NULL,
   NAME VARCHAR(32) NOT NULL,
   PASSWORD VARCHAR(32) NOT NULL,
   ROLE VARCHAR(7) DEFAULT 'REGULAR' NOT NULL
     CHECK (ROLE IN ('ADMIN', 'REGULAR', 'GUEST')),
   CREATED DATE
)
